const cron = require('node-cron');
const Review = require('./models/Review');
const mongoose = require('mongoose');

const reviewPool = [
    { name: "Amit K.", comment: "Best trading course ever! Highly recommended.", rating: 5 },
    { name: "Sana S.", comment: "Pehle loss hota tha, ab consistent profit ho raha hai.", rating: 5 },
    { name: "Rahul J.", comment: "Concepts bahut clearly samjhaye gaye hain.", rating: 4 },
    { name: "Priya M.", comment: "Genuine platform for serious traders.", rating: 5 },
    { name: "Vikas T.", comment: "Option buying ka confidence aa gaya.", rating: 5 },
    { name: "Neha R.", comment: "Risk management ka part best laga.", rating: 5 },
    { name: "Arjun P.", comment: "Strategy simple aur effective hai.", rating: 4 },
    { name: "Karan D.", comment: "Live examples se samajhna easy ho gaya.", rating: 5 },
    { name: "Sneha A.", comment: "Ab random trading nahi karta, proper setup follow karta hu.", rating: 5 },
    { name: "Rohit S.", comment: "Premium behavior samajh aa gaya.", rating: 4 },
    { name: "Manish G.", comment: "Support team bhi fast response deti hai.", rating: 5 },
    { name: "Pooja N.", comment: "Course worth every rupee.", rating: 5 },
    { name: "Deepak B.", comment: "Breakout strategy mast kaam karti hai.", rating: 5 },
    { name: "Riya K.", comment: "Simple language me sab explain hai.", rating: 4 },
    { name: "Nikhil V.", comment: "Intraday ke liye best guide mila.", rating: 5 },
    { name: "Anjali S.", comment: "Confidence boost ho gaya trading me.", rating: 5 },
    { name: "Tarun M.", comment: "FOMO control karna seekh gaya.", rating: 4 },
    { name: "Simran K.", comment: "Ab proper entries leta hu.", rating: 5 },
    { name: "Alok J.", comment: "Loss kam ho gaya kaafi.", rating: 5 },
    { name: "Vivek T.", comment: "Beginner friendly content hai.", rating: 4 },
    { name: "Rakesh P.", comment: "Option chain samajh aa gaya finally.", rating: 5 },
    { name: "Sunita L.", comment: "Ab blindly trade nahi karti.", rating: 5 },
    { name: "Harish R.", comment: "Discipline improve hua hai.", rating: 5 },
    { name: "Divya S.", comment: "Best for intraday traders.", rating: 4 },
    { name: "Radha Kumari", comment: "Ab profit mil raha hai regularly.", rating: 5 },
    { name: "Gita Sharma", comment: "Strategy simple hai.", rating: 5 },
    { name: "Alka Singh", comment: "अब FOMO nahi hota.", rating: 5 },
    { name: "Rekha Gupta", comment: "अब proper setup follow karti hu.", rating: 5 },
    { name: "Manju Verma", comment: "Learning kaafi achhi hai.", rating: 5 },
    { name: "Kusum Devi", comment: "Ab loss kaafi kam ho gaya.", rating: 5 },
    { name: "Sarla Yadav", comment: "Confidence aa gaya trading me.", rating: 5 },
    { name: "Beena Patel", comment: "अब entry perfect hoti hai.", rating: 5 },
    { name: "Pushpa Jain", comment: "Best trading guidance mila.", rating: 5 },
    { name: "Chanda Gupta", comment: "Ab market ka fear nahi hai.", rating: 5 },
    { name: "Lokesh G.", comment: "Real market example helpful hai.", rating: 5 },
    { name: "Naveen K.", comment: "Strategy practical hai, theory nahi.", rating: 5 },
    { name: "Suresh B.", comment: "Consistency aane lagi hai.", rating: 5 },
    { name: "Anu J.", comment: "Trading mindset improve hua.", rating: 4 },
    { name: "Kavita D.", comment: "Highly useful content.", rating: 5 },
    { name: "Meena I.", comment: "Loss recover kar payi.", rating: 5 },
    { name: "Trader101", comment: "Ab entry aur exit clear ho gaya.", rating: 5 },
    { name: "Trader102", comment: "Scalping ke liye best tricks mile.", rating: 4 },
    { name: "Trader103", comment: "Market ka fear khatam ho gaya.", rating: 5 },
    { name: "Trader104", comment: "Learning experience awesome raha.", rating: 5 },
    { name: "Trader105", comment: "Price action samajh aa gaya.", rating: 5 },
    { name: "Trader106", comment: "Indicators use karna sikh liya.", rating: 4 },
    { name: "Trader107", comment: "Ab emotional trading nahi karta.", rating: 5 },
    { name: "Trader108", comment: "Best investment for learning.", rating: 5 },
    { name: "Trader109", comment: "Strategy backtested hai.", rating: 5 },
    { name: "Trader110", comment: "Profit consistency badh rahi hai.", rating: 5 },
    { name: "Trader111", comment: "Course simple aur powerful hai.", rating: 5 },
    { name: "Trader112", comment: "Har cheez step by step hai.", rating: 4 },
    { name: "Trader113", comment: "Support bhi helpful hai.", rating: 5 },
    { name: "Trader114", comment: "Best for beginners.", rating: 5 },
    { name: "Trader115", comment: "Live trading help mili.", rating: 5 },
    { name: "Rohit K.", comment: "Ab trade lene se pehle clear plan hota hai.", rating: 5 },
    { name: "Ankit S.", comment: "Market structure samajh aa gaya.", rating: 5 },
    { name: "Pankaj M.", comment: "Loss control karna seekh gaya.", rating: 5 },
    { name: "Deepika R.", comment: "Simple aur effective strategy hai.", rating: 4 },
    { name: "Gaurav T.", comment: "Ab overtrading nahi karta.", rating: 5 },
    { name: "Nisha P.", comment: "Confidence build hua hai.", rating: 5 },
    { name: "Abhishek J.", comment: "Breakout ka timing samajh aaya.", rating: 5 },
    { name: "Komal D.", comment: "Best learning experience mila.", rating: 5 },
    { name: "Yash V.", comment: "Indicators ka sahi use seekha.", rating: 4 },
    { name: "Siddharth K.", comment: "Ab loss recover kar pa raha hu.", rating: 5 },
    { name: "Ritu S.", comment: "Course beginner friendly hai.", rating: 5 },
    { name: "Mohit G.", comment: "Ab market ka fear nahi lagta.", rating: 5 },
    { name: "Shivam T.", comment: "Entry aur exit clear ho gaya.", rating: 5 },
    { name: "Aarti M.", comment: "Price action mast samjhaya hai.", rating: 5 },
    { name: "Nitin B.", comment: "Strategy kaafi profitable hai.", rating: 5 },
    { name: "Pooja K.", comment: "Trading discipline improve hua.", rating: 5 },
    { name: "Varun R.", comment: "Ab emotional trading nahi karta.", rating: 5 },
    { name: "Kajal S.", comment: "Real examples helpful lage.", rating: 4 },
    { name: "Sumit J.", comment: "Intraday ke liye best hai.", rating: 5 },
    { name: "Reena D.", comment: "Concepts clear ho gaye.", rating: 5 },
    { name: "Aditya N.", comment: "अब ट्रेडिंग में clarity आ गई है.", rating: 5 },
    { name: "Mehul P.", comment: "Setup identify karna easy ho gaya.", rating: 5 },
    { name: "Rashmi T.", comment: "Loss kaafi kam ho gaya.", rating: 5 },
    { name: "Kunal S.", comment: "अब सही entry लेने लगा हूँ.", rating: 5 },
    { name: "Swati G.", comment: "Highly recommended for traders.", rating: 5 },
    { name: "Dinesh V.", comment: "Support bhi fast milta hai.", rating: 5 },
    { name: "Aman K.", comment: "अब market ka logic samajh aa gaya.", rating: 5 },
    { name: "Heena R.", comment: "Very useful content.", rating: 4 },
    { name: "Ravi M.", comment: "अब confidence ke sath trade karta hu.", rating: 5 },
    { name: "Seema L.", comment: "Best course for intraday.", rating: 5 },
    { name: "Ashish T.", comment: "अब random trading band kar di.", rating: 5 },
    { name: "Preeti J.", comment: "Concepts easy language me hai.", rating: 5 },
    { name: "Vishal D.", comment: "Strategy kaafi strong hai.", rating: 5 },
    { name: "Neeraj K.", comment: "Ab loss control ho raha hai.", rating: 5 },
    { name: "Bhavna S.", comment: "Trading mindset improve hua.", rating: 5 },
    { name: "Rohini P.", comment: "अब patience aaya hai trading me.", rating: 5 },
    { name: "Anurag M.", comment: "Best learning platform.", rating: 5 },
    { name: "Tanya R.", comment: "अब FOMO control kar leti hu.", rating: 5 },
    { name: "Harsh V.", comment: "Entry aur exit ka clarity mil gaya.", rating: 5 },
    { name: "Jyoti K.", comment: "Real market examples best hai.", rating: 5 },
    { name: "Dev S.", comment: "अब trading easy lagne lagi hai.", rating: 5 },
    { name: "Priti G.", comment: "Simple aur practical course.", rating: 5 },
    { name: "Naveen D.", comment: "Ab loss se dar nahi lagta.", rating: 5 },
    { name: "Aakash T.", comment: "Strategy kaafi useful hai.", rating: 5 },
    { name: "Shreya M.", comment: "अब disciplined trading kar rahi hu.", rating: 5 },
    { name: "Kapil R.", comment: "अब entry lene me confidence hai.", rating: 5 },
    { name: "Monika S.", comment: "Best investment learning ke liye.", rating: 5 },
    { name: "Rajeev K.", comment: "अब consistent profit aa raha hai.", rating: 5 },
    { name: "Sonal P.", comment: "Concepts bahut clear hai.", rating: 5 },
    { name: "Imran J.", comment: "अब overtrading nahi karta.", rating: 5 },
    { name: "Farhan A.", comment: "Strategy simple aur powerful hai.", rating: 5 },
    { name: "Chirag V.", comment: "अब सही setup wait karta hu.", rating: 5 },
    { name: "Latika R.", comment: "अब trading ka fear khatam ho gaya.", rating: 5 },
    { name: "Manoj S.", comment: "Best intraday guidance mila.", rating: 5 },
    { name: "Kriti N.", comment: "अब loss control me hai.", rating: 5 },
    { name: "Rahul T.", comment: "Entry timing perfect ho raha hai.", rating: 5 },
    { name: "Nikita P.", comment: "Course kaafi helpful hai.", rating: 5 },
    { name: "Arvind K.", comment: "अब clear strategy follow karta hu.", rating: 5 },
    { name: "Shalini G.", comment: "अब emotional trading nahi karti.", rating: 5 },
    { name: "Prakash D.", comment: "Best trading सीखने का तरीका.", rating: 5 },
    { name: "User101", comment: "अब trade lene ka confidence aa gaya.", rating: 5 },
    { name: "User102", comment: "Loss kam ho raha hai.", rating: 5 },
    { name: "User103", comment: "Ab consistent profit mil raha hai.", rating: 5 },
    { name: "User104", comment: "Simple aur powerful strategy.", rating: 5 },
    { name: "User105", comment: "Best trading course.", rating: 5 },
    { name: "User106", comment: "अब overtrading band.", rating: 5 },
    { name: "User107", comment: "Clear entry exit system.", rating: 5 },
    { name: "User108", comment: "Highly recommended.", rating: 5 },
    { name: "User109", comment: "Ab market samajh aa raha hai.", rating: 5 },
    { name: "User110", comment: "Profit consistency badh rahi hai.", rating: 5 },
    { name: "Rohan S.", comment: "Ab har trade planned hota hai.", rating: 5 },
    { name: "Ayesha K.", comment: "Concepts bahut easily samajh aaye.", rating: 5 },
    { name: "Mukesh R.", comment: "अब loss control karna easy ho gaya.", rating: 5 },
    { name: "Kiran P.", comment: "Strategy kaafi powerful hai.", rating: 5 },
    { name: "Sunita Rani", comment: "अब trade lene me dar nahi lagta.", rating: 5 },
    { name: "Seema Agarwal", comment: "Strategy kaafi useful hai.", rating: 5 },
    { name: "Mamta Singh", comment: "Ab patience aa gaya.", rating: 5 },
    { name: "Rekha Sharma", comment: "Best learning platform.", rating: 5 },
    { name: "Lata Verma", comment: "अब emotional decisions nahi leti.", rating: 5 },
    { name: "Sarita Yadav", comment: "Ab loss control me hai.", rating: 5 },
    { name: "Usha Patel", comment: "Clear entry exit system mila.", rating: 5 },
    { name: "Indu Gupta", comment: "Ab market samajh aa raha hai.", rating: 5 },
    { name: "Kamla Devi", comment: "अब trading me confidence hai.", rating: 5 },
    { name: "Savita Mishra", comment: "Best course for beginners.", rating: 5 },
    { name: "Vivek S.", comment: "अब blindly trade nahi karta.", rating: 5 },
    { name: "Heena M.", comment: "Best course for beginners.", rating: 5 },
    { name: "Saurabh J.", comment: "Entry ka timing improve hua.", rating: 5 },
    { name: "Ritu G.", comment: "अब patience aa gaya hai trading me.", rating: 5 },
    { name: "Nikhil P.", comment: "अब setup ka wait karta hu.", rating: 5 },
    { name: "Neelam Mishra", comment: "अब clear plan ke sath trade karti hu.", rating: 5 },
    { name: "Pinky Kumari", comment: "Learning experience awesome raha.", rating: 5 },
    { name: "Geeta Devi", comment: "Ab profit consistency aa rahi hai.", rating: 5 },
    { name: "Nikita Choudhary", comment: "Ab entry lene me clarity hai.", rating: 5 },
    { name: "Shalini Verma", comment: "अब loss ka dar nahi lagta.", rating: 5 },
    { name: "Ayesha Khan", comment: "Strategy practical hai.", rating: 5 },
    { name: "Rohini Iyer", comment: "Ab disciplined trading karti hu.", rating: 5 },
    { name: "Latika Gupta", comment: "Best intraday strategy mili.", rating: 5 },
    { name: "Suman Yadav", comment: "अब overtrading nahi karti.", rating: 5 },
    { name: "Chhavi Jain", comment: "Confidence kaafi badh gaya.", rating: 5 },
    { name: "Pallavi S.", comment: "Simple aur effective teaching style.", rating: 4 },
    { name: "Anuj K.", comment: "अब consistent profit mil raha hai.", rating: 5 },
    { name: "Bhavna Soni", comment: "Loss control ho gaya.", rating: 5 },
    { name: "Reena Pillai", comment: "अब FOMO control kar liya.", rating: 5 },
    { name: "Pallavi Nair", comment: "अब confidence ke sath trade karti hu.", rating: 5 },
    { name: "Anu Joseph", comment: "Concepts clear ho gaye.", rating: 5 },
    { name: "Kiran Shetty", comment: "Best course ever.", rating: 5 },
    { name: "Snehal R.", comment: "Course kaafi helpful hai.", rating: 5 },
    { name: "Ramesh T.", comment: "अब overtrading nahi karta.", rating: 5 },
    { name: "Jyoti M.", comment: "Best learning platform.", rating: 5 },
    { name: "Gaurav S.", comment: "अब market ka logic samajh aata hai.", rating: 5 },
    { name: "Nisha K.", comment: "Confidence build hua hai.", rating: 5 },
    { name: "Sonal Bansal", comment: "Ab market ka logic samajh aa gaya.", rating: 5 },
    { name: "Preeti Joshi", comment: "अब consistent profit mil raha hai.", rating: 5 },
    { name: "Ritu Chauhan", comment: "Entry timing improve hua.", rating: 5 },
    { name: "Monika Arora", comment: "Best investment for learning.", rating: 5 },
    { name: "Jyoti Pandey", comment: "Ab trading easy lagne lagi hai.", rating: 5 },
    { name: "Aditya R.", comment: "अब trade lene me dar nahi lagta.", rating: 5 },
    { name: "Kavya P.", comment: "Real examples se clarity mili.", rating: 5 },
    { name: "Harshit S.", comment: "अब emotional trading band.", rating: 5 },
    { name: "Komal K.", comment: "Strategy easy aur practical hai.", rating: 5 },
    { name: "Komal Saxena", comment: "Best intraday learning mila.", rating: 5 },
    { name: "Divya Reddy", comment: "Ab loss recover kar pa rahi hu.", rating: 5 },
    { name: "Heena Khan", comment: "Best platform for learning trading.", rating: 5 },
    { name: "Shreya Das", comment: "अब patience aa gaya hai.", rating: 5 },
    { name: "Tanya Kapoor", comment: "Strategy kaafi powerful hai.", rating: 5 },
    { name: "Rashmi Tiwari", comment: "अब emotional trading nahi karti.", rating: 5 },
    { name: "Deepika Sharma", comment: "Confidence boost ho gaya.", rating: 5 },
    { name: "Kajal Singh", comment: "अब random trading nahi karti.", rating: 5 },
    { name: "Meena Iyer", comment: "Concepts bahut easy hain.", rating: 5 },
    { name: "Aarti Mishra", comment: "अब disciplined trading karti hu.", rating: 5 },
    { name: "Swati Jain", comment: "Loss kaafi kam ho gaya.", rating: 5 },
    { name: "Nisha Agarwal", comment: "Ab proper setup ka wait karti hu.", rating: 5 },
    { name: "Amitabh D.", comment: "अब loss recover ho raha hai.", rating: 5 },
    { name: "Shweta J.", comment: "Concepts clear ho gaye.", rating: 5 },
    { name: "Riya Mehta", comment: "Strategy simple aur effective hai.", rating: 5 },
    { name: "Kavita Yadav", comment: "Ab entry aur exit clear ho gaya.", rating: 5 },
    { name: "Simran Kaur", comment: "Trading ka fear khatam ho gaya.", rating: 5 },
    { name: "Varsha R.", comment: "अब disciplined trading karti hu.", rating: 5 },
    { name: "Puneet K.", comment: "अब entry perfect ho rahi hai.", rating: 5 },
    { name: "Sameer P.", comment: "Intraday ke liye best guidance.", rating: 5 },
    { name: "Pooja Singh", comment: "Ab trade lene me confidence aa gaya.", rating: 5 },
    { name: "Anjali Gupta", comment: "Best course for beginners.", rating: 5 },
    { name: "Sneha Patel", comment: "Ab overtrading band kar di.", rating: 5 },
    { name: "Divyansh S.", comment: "अब FOMO control kar liya.", rating: 5 },
    { name: "Ankita M.", comment: "Very useful content.", rating: 4 },
    { name: "Manav K.", comment: "अब clear strategy follow karta hu.", rating: 5 },
    { name: "Priya Sharma", comment: "Pehle loss hota tha, ab consistent profit ho raha hai.", rating: 5 },
    { name: "Neha Verma", comment: "Concepts bahut clearly samjhaye gaye hain.", rating: 5 },
    { name: "Ragini T.", comment: "Best investment for learning.", rating: 5 },
    { name: "Sandeep V.", comment: "अब profit consistency aa rahi hai.", rating: 5 },
];

// Har 3 ghante me ek baar chalega (0 */3 * * *)

cron.schedule('* * * * *', async () => {
      try {
        // Pool check
        if (!reviewPool || reviewPool.length === 0) {
            console.log("❌ Error: reviewPool khali hai!");
            return;
        }

        // Random review pick karo
        const randomData = reviewPool[Math.floor(Math.random() * reviewPool.length)];
        
        // Direct Database Entry
        await Review.collection.insertOne({
            username: randomData.username,
            name: randomData.username, 
            rating: randomData.rating,
            comment: randomData.comment,
            userId: new mongoose.Types.ObjectId(),
            status: 'approved',
            createdAt: new Date()
        });

        console.log("✅ SUCCESS: Random Review Posted -", randomData.username);
    } catch (err) {
        console.error("❌ DB Error:", err.message);
    }
});

