const cron = require("node-cron");
const Review = require("./models/Review");
const mongoose = require("mongoose");

const reviewPool = [
  {
    name: "Amit K.",
    comment: "Best trading course ever! Highly recommended.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=jyoti",
  },
  {
    name: "Sana S.",
    comment: "Pehle loss hota tha, ab consistent profit ho raha hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=sana",
  },
  {
    name: "Rahul J.",
    comment: "Concepts bahut clearly samjhaye gaye hain.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=rahul",
  },
  {
    name: "Priya M.",
    comment: "Genuine platform for serious traders.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=priya",
  },
  {
    name: "Vikas T.",
    comment: "Option buying ka confidence aa gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=vikas",
  },
  {
    name: "Neha R.",
    comment: "Risk management ka part best laga.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=neha",
  },
  {
    name: "Arjun P.",
    comment: "Strategy simple aur effective hai.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=arjun",
  },
  {
    name: "Karan D.",
    comment: "Live examples se samajhna easy ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=karan",
  },
  {
    name: "Sneha A.",
    comment: "Ab random trading nahi karta, proper setup follow karta hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=sneha",
  },
  {
    name: "Rohit S.",
    comment: "Premium behavior samajh aa gaya.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=rohit",
  },
  {
    name: "Manish G.",
    comment: "Support team bhi fast response deti hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=manish",
  },
  {
    name: "Pooja N.",
    comment: "Course worth every rupee.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=pooja",
  },
  {
    name: "Deepak B.",
    comment: "Breakout strategy mast kaam karti hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=deepak",
  },
  {
    name: "Riya K.",
    comment: "Simple language me sab explain hai.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=riya",
  },
  {
    name: "Nikhil V.",
    comment: "Intraday ke liye best guide mila.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=nikhil",
  },
  {
    name: "Anjali S.",
    comment: "Confidence boost ho gaya trading me.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=anjali",
  },
  {
    name: "Tarun M.",
    comment: "FOMO control karna seekh gaya.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=tarun",
  },
  {
    name: "Simran K.",
    comment: "Ab proper entries leta hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=simran",
  },
  {
    name: "Alok J.",
    comment: "Loss kam ho gaya kaafi.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=alok",
  },
  {
    name: "Vivek T.",
    comment: "Beginner friendly content hai.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=vivek",
  },
  {
    name: "Rakesh P.",
    comment: "Option chain samajh aa gaya finally.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rakesh",
  },
  {
    name: "Sunita L.",
    comment: "Ab blindly trade nahi karti.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=sunita",
  },
  {
    name: "Harish R.",
    comment: "Discipline improve hua hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=harish",
  },
  {
    name: "Divya S.",
    comment: "Best for intraday traders.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=divya",
  },
  {
    name: "Radha Kumari",
    comment: "Ab profit mil raha hai regularly.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=radha",
  },
  {
    name: "Gita Sharma",
    comment: "Strategy simple hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=gita",
  },
  {
    name: "Alka Singh",
    comment: "अब FOMO nahi hota.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=alka",
  },
  {
    name: "Rekha Gupta",
    comment: "अब proper setup follow karti hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rekha",
  },
  {
    name: "Manju Verma",
    comment: "Learning kaafi achhi hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=manju",
  },
  {
    name: "Kusum Devi",
    comment: "Ab loss kaafi kam ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=kusum",
  },
  {
    name: "Sarla Yadav",
    comment: "Confidence aa gaya trading me.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=sarla",
  },
  {
    name: "Beena Patel",
    comment: "अब entry perfect hoti hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=beena",
  },
  {
    name: "Pushpa Jain",
    comment: "Best trading guidance mila.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=pushpa",
  },
  {
    name: "Chanda Gupta",
    comment: "Ab market ka fear nahi hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=chanda",
  },
  {
    name: "Lokesh G.",
    comment: "Real market example helpful hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=lokesh",
  },
  {
    name: "Naveen K.",
    comment: "Strategy practical hai, theory nahi.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=naveen",
  },
  {
    name: "Suresh B.",
    comment: "Consistency aane lagi hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=suresh",
  },
  {
    name: "Anu J.",
    comment: "Trading mindset improve hua.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=anu",
  },
  {
    name: "Kavita D.",
    comment: "Highly useful content.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=kavita",
  },
  {
    name: "Meena I.",
    comment: "Loss recover kar payi.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=meena",
  },
  {
    name: "Arjun Mehta",
    comment: "Ab entry aur exit clear ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=arjun",
  },
  {
    name: "Rohit Sharma",
    comment: "Scalping ke liye best tricks mile.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=rohit",
  },
  {
    name: "Vivek Gupta",
    comment: "Market ka fear khatam ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=vivek",
  },
  {
    name: "Siddharth Jain",
    comment: "Learning experience awesome raha.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=siddharth",
  },
  {
    name: "Karan Singh",
    comment: "Price action samajh aa gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=karan",
  },
  {
    name: "Amit Verma",
    comment: "Indicators use karna sikh liya.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=amit",
  },
  {
    name: "Nitin Yadav",
    comment: "Ab emotional trading nahi karta.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=nitin",
  },
  {
    name: "Harsh Agarwal",
    comment: "Best investment for learning.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=harsh",
  },
  {
    name: "Manish Patel",
    comment: "Strategy backtested hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=manish",
  },
  {
    name: "Deepak Kumar",
    comment: "Profit consistency badh rahi hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=deepak",
  },
  {
    name: "Ankit Sharma",
    comment: "Course simple aur powerful hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ankit",
  },
  {
    name: "Rahul Jain",
    comment: "Har cheez step by step hai.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=rahul",
  },
  {
    name: "Pankaj Gupta",
    comment: "Support bhi helpful hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=pankaj",
  },
  {
    name: "Saurabh Mishra",
    comment: "Best for beginners.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=saurabh",
  },
  {
    name: "Yash Verma",
    comment: "Live trading help mili.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=yash",
  },
  {
    name: "Rohit K.",
    comment: "Ab trade lene se pehle clear plan hota hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rohit",
  },
  {
    name: "Ankit S.",
    comment: "Market structure samajh aa gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ankit",
  },
  {
    name: "Pankaj M.",
    comment: "Loss control karna seekh gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=pankaj",
  },
  {
    name: "Deepika R.",
    comment: "Simple aur effective strategy hai.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=deepika",
  },
  {
    name: "Gaurav T.",
    comment: "Ab overtrading nahi karta.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=gaurav",
  },
  {
    name: "Nisha P.",
    comment: "Confidence build hua hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=nisha",
  },
  {
    name: "Abhishek J.",
    comment: "Breakout ka timing samajh aaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=abhishek",
  },
  {
    name: "Komal D.",
    comment: "Best learning experience mila.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=komal",
  },
  {
    name: "Yash V.",
    comment: "Indicators ka sahi use seekha.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=yash",
  },
  {
    name: "Siddharth K.",
    comment: "Ab loss recover kar pa raha hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=siddharth",
  },
  {
    name: "Ritu S.",
    comment: "Course beginner friendly hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ritu",
  },
  {
    name: "Mohit G.",
    comment: "Ab market ka fear nahi lagta.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=mohit",
  },
  {
    name: "Shivam T.",
    comment: "Entry aur exit clear ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=shivam",
  },
  {
    name: "Aarti M.",
    comment: "Price action mast samjhaya hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=aarti",
  },
  {
    name: "Nitin B.",
    comment: "Strategy kaafi profitable hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=nitin",
  },
  {
    name: "Pooja K.",
    comment: "Trading discipline improve hua.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=pooja",
  },
  {
    name: "Varun R.",
    comment: "Ab emotional trading nahi karta.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=varun",
  },
  {
    name: "Kajal S.",
    comment: "Real examples helpful lage.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=kajal",
  },
  {
    name: "Sumit J.",
    comment: "Intraday ke liye best hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=sumit",
  },
  {
    name: "Reena D.",
    comment: "Concepts clear ho gaye.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=reena",
  },
  {
    name: "Aditya N.",
    comment: "अब ट्रेडिंग में clarity आ गई है.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=aditya",
  },
  {
    name: "Mehul P.",
    comment: "Setup identify karna easy ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=mehul",
  },
  {
    name: "Rashmi T.",
    comment: "Loss kaafi kam ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rashmi",
  },
  {
    name: "Kunal S.",
    comment: "अब सही entry लेने लगा हूँ.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=kunal",
  },
  {
    name: "Swati G.",
    comment: "Highly recommended for traders.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=swati",
  },
  {
    name: "Dinesh V.",
    comment: "Support bhi fast milta hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=dinesh",
  },
  {
    name: "Aman K.",
    comment: "अब market ka logic samajh aa gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=aman",
  },
  {
    name: "Heena R.",
    comment: "Very useful content.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=heena",
  },
  {
    name: "Ravi M.",
    comment: "अब confidence ke sath trade karta hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ravi",
  },
  {
    name: "Seema L.",
    comment: "Best course for intraday.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=seema",
  },
  {
    name: "Ashish T.",
    comment: "अब random trading band kar di.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ashish",
  },
  {
    name: "Preeti J.",
    comment: "Concepts easy language me hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=preeti",
  },
  {
    name: "Vishal D.",
    comment: "Strategy kaafi strong hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=vishal",
  },
  {
    name: "Neeraj K.",
    comment: "Ab loss control ho raha hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=neeraj",
  },
  {
    name: "Bhavna S.",
    comment: "Trading mindset improve hua.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=bhavna",
  },
  {
    name: "Rohini P.",
    comment: "अब patience aaya hai trading me.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rohini",
  },
  {
    name: "Anurag M.",
    comment: "Best learning platform.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=anurag",
  },
  {
    name: "Tanya R.",
    comment: "अब FOMO control kar leti hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=tanya",
  },
  {
    name: "Harsh V.",
    comment: "Entry aur exit ka clarity mil gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=harsh",
  },
  {
    name: "Jyoti K.",
    comment: "Real market examples best hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=jyoti",
  },
  {
    name: "Dev S.",
    comment: "अब trading easy lagne lagi hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=dev",
  },
  {
    name: "Priti G.",
    comment: "Simple aur practical course.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=priti",
  },
  {
    name: "Naveen D.",
    comment: "Ab loss se dar nahi lagta.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=naveen",
  },
  {
    name: "Aakash T.",
    comment: "Strategy kaafi useful hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=aakash",
  },
  {
    name: "Shreya M.",
    comment: "अब disciplined trading kar rahi hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=shreya",
  },
  {
    name: "Kapil R.",
    comment: "अब entry lene me confidence hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=kapil",
  },
  {
    name: "Monika S.",
    comment: "Best investment learning ke liye.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=monika",
  },
  {
    name: "Rajeev K.",
    comment: "अब consistent profit aa raha hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rajeev",
  },
  {
    name: "Sonal P.",
    comment: "Concepts bahut clear hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=sonal",
  },
  {
    name: "Imran J.",
    comment: "अब overtrading nahi karta.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=imran",
  },
  {
    name: "Farhan A.",
    comment: "Strategy simple aur powerful hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=farhan",
  },
  {
    name: "Chirag V.",
    comment: "अब सही setup wait karta hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=chirag",
  },
  {
    name: "Latika R.",
    comment: "अब trading ka fear khatam ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=latika",
  },
  {
    name: "Manoj S.",
    comment: "Best intraday guidance mila.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=manoj",
  },
  {
    name: "Kriti N.",
    comment: "अब loss control me hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=krati",
  },
  {
    name: "Rahul T.",
    comment: "Entry timing perfect ho raha hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rahul",
  },
  {
    name: "Nikita P.",
    comment: "Course kaafi helpful hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=nikita",
  },
  {
    name: "Arvind K.",
    comment: "अब clear strategy follow karta hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=arvind",
  },
  {
    name: "Shalini G.",
    comment: "अब emotional trading nahi karti.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=shalini",
  },
  {
    name: "Prakash D.",
    comment: "Best trading सीखने का तरीका.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=prakash",
  },
  {
    name: "Aditya Sharma",
    comment: "अब trade lene ka confidence aa gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=aditya",
  },
  {
    name: "Rohit Verma",
    comment: "Loss kam ho raha hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rohit",
  },
  {
    name: "Kunal Gupta",
    comment: "Ab consistent profit mil raha hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=kunal",
  },
  {
    name: "Aman Singh",
    comment: "Simple aur powerful strategy.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=aman",
  },
  {
    name: "Nikhil Jain",
    comment: "Best trading course.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=nikhil",
  },
  {
    name: "Vikas Yadav",
    comment: "अब overtrading band.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=vikas",
  },
  {
    name: "Harsh Patel",
    comment: "Clear entry exit system.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=harsh",
  },
  {
    name: "Saurabh Mishra",
    comment: "Highly recommended.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=saurabh",
  },
  {
    name: "Rahul Kumar",
    comment: "Ab market samajh aa raha hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rahul",
  },
  {
    name: "User110",
    comment: "Profit consistency badh rahi hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=user110",
  },
  {
    name: "Rohan S.",
    comment: "Ab har trade planned hota hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rohan",
  },
  {
    name: "Ayesha K.",
    comment: "Concepts bahut easily samajh aaye.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ayesha",
  },
  {
    name: "Mukesh R.",
    comment: "अब loss control karna easy ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=mukesh",
  },
  {
    name: "Kiran P.",
    comment: "Strategy kaafi powerful hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=kiran",
  },
  {
    name: "Sunita Rani",
    comment: "अब trade lene me dar nahi lagta.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=sunita",
  },
  {
    name: "Seema Agarwal",
    comment: "Strategy kaafi useful hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=seema",
  },
  {
    name: "Mamta Singh",
    comment: "Ab patience aa gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=mamta",
  },
  {
    name: "Rekha Sharma",
    comment: "Best learning platform.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rekha",
  },
  {
    name: "Lata Verma",
    comment: "अब emotional decisions nahi leti.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=lata",
  },
  {
    name: "Sarita Yadav",
    comment: "Ab loss control me hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=sarita",
  },
  {
    name: "Usha Patel",
    comment: "Clear entry exit system mila.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=usha",
  },
  {
    name: "Indu Gupta",
    comment: "Ab market samajh aa raha hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=indu",
  },
  {
    name: "Kamla Devi",
    comment: "अब trading me confidence hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=kamla",
  },
  {
    name: "Savita Mishra",
    comment: "Best course for beginners.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=savita",
  },
  {
    name: "Vivek S.",
    comment: "अब blindly trade nahi karta.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=vivek",
  },
  {
    name: "Heena M.",
    comment: "Best course for beginners.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=heena",
  },
  {
    name: "Saurabh J.",
    comment: "Entry ka timing improve hua.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=saurabh",
  },
  {
    name: "Ritu G.",
    comment: "अब patience aa gaya hai trading me.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ritu",
  },
  {
    name: "Nikhil P.",
    comment: "अब setup ka wait karta hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=nikhil",
  },
  {
    name: "Neelam Mishra",
    comment: "अब clear plan ke sath trade karti hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=neelam",
  },
  {
    name: "Pinky Kumari",
    comment: "Learning experience awesome raha.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=pinky",
  },
  {
    name: "Geeta Devi",
    comment: "Ab profit consistency aa rahi hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=geeta",
  },
  {
    name: "Nikita Choudhary",
    comment: "Ab entry lene me clarity hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=nikita",
  },
  {
    name: "Shalini Verma",
    comment: "अब loss ka dar nahi lagta.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=shalini",
  },
  {
    name: "Ayesha Khan",
    comment: "Strategy practical hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ayesha",
  },
  {
    name: "Rohini Iyer",
    comment: "Ab disciplined trading karti hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rohini",
  },
  {
    name: "Latika Gupta",
    comment: "Best intraday strategy mili.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=latika",
  },
  {
    name: "Suman Yadav",
    comment: "अब overtrading nahi karti.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=suman",
  },
  {
    name: "Chhavi Jain",
    comment: "Confidence kaafi badh gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=chhavi",
  },
  {
    name: "Pallavi S.",
    comment: "Simple aur effective teaching style.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=pallavi",
  },
  {
    name: "Anuj K.",
    comment: "अब consistent profit mil raha hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=anuj",
  },
  {
    name: "Bhavna Soni",
    comment: "Loss control ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=bhavna",
  },
  {
    name: "Reena Pillai",
    comment: "अब FOMO control kar liya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=reena",
  },
  {
    name: "Pallavi Nair",
    comment: "अब confidence ke sath trade karti hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=pallavi",
  },
  {
    name: "Anu Joseph",
    comment: "Concepts clear ho gaye.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=anu",
  },
  {
    name: "Kiran Shetty",
    comment: "Best course ever.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=kiran",
  },
  {
    name: "Snehal R.",
    comment: "Course kaafi helpful hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=snehal",
  },
  {
    name: "Ramesh T.",
    comment: "अब overtrading nahi karta.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ramesh",
  },
  {
    name: "Jyoti M.",
    comment: "Best learning platform.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=jyoti",
  },
  {
    name: "Gaurav S.",
    comment: "अब market ka logic samajh aata hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=gaurav",
  },
  {
    name: "Nisha K.",
    comment: "Confidence build hua hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=nisha",
  },
  {
    name: "Sonal Bansal",
    comment: "Ab market ka logic samajh aa gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=sonal",
  },
  {
    name: "Preeti Joshi",
    comment: "अब consistent profit mil raha hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=preeti",
  },
  {
    name: "Ritu Chauhan",
    comment: "Entry timing improve hua.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ritu",
  },
  {
    name: "Monika Arora",
    comment: "Best investment for learning.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=monika",
  },
  {
    name: "Jyoti Pandey",
    comment: "Ab trading easy lagne lagi hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=jyoti",
  },
  {
    name: "Aditya R.",
    comment: "अब trade lene me dar nahi lagta.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=aditya",
  },
  {
    name: "Kavya P.",
    comment: "Real examples se clarity mili.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=kavya",
  },
  {
    name: "Harshit S.",
    comment: "अब emotional trading band.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=harshit",
  },
  {
    name: "Komal K.",
    comment: "Strategy easy aur practical hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=komal",
  },
  {
    name: "Komal Saxena",
    comment: "Best intraday learning mila.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=komal",
  },
  {
    name: "Divya Reddy",
    comment: "Ab loss recover kar pa rahi hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=divya",
  },
  {
    name: "Heena Khan",
    comment: "Best platform for learning trading.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=heena",
  },
  {
    name: "Shreya Das",
    comment: "अब patience aa gaya hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=shreya",
  },
  {
    name: "Tanya Kapoor",
    comment: "Strategy kaafi powerful hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=tanya",
  },
  {
    name: "Rashmi Tiwari",
    comment: "अब emotional trading nahi karti.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rashmi",
  },
  {
    name: "Deepika Sharma",
    comment: "Confidence boost ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=deepika",
  },
  {
    name: "Kajal Singh",
    comment: "अब random trading nahi karti.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=kajal",
  },
  {
    name: "Meena Iyer",
    comment: "Concepts bahut easy hain.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=meena",
  },
  {
    name: "Aarti Mishra",
    comment: "अब disciplined trading karti hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=aarti",
  },
  {
    name: "Swati Jain",
    comment: "Loss kaafi kam ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=swati",
  },
  {
    name: "Nisha Agarwal",
    comment: "Ab proper setup ka wait karti hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=nisha",
  },
  {
    name: "Amitabh D.",
    comment: "अब loss recover ho raha hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=amitabh",
  },
  {
    name: "Shweta J.",
    comment: "Concepts clear ho gaye.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=shweta",
  },
  {
    name: "Riya Mehta",
    comment: "Strategy simple aur effective hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=riya",
  },
  {
    name: "Kavita Yadav",
    comment: "Ab entry aur exit clear ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=kavita",
  },
  {
    name: "Simran Kaur",
    comment: "Trading ka fear khatam ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=simran",
  },
  {
    name: "Varsha R.",
    comment: "अब disciplined trading karti hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=varsha",
  },
  {
    name: "Puneet K.",
    comment: "अब entry perfect ho rahi hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=puneet",
  },
  {
    name: "Sameer P.",
    comment: "Intraday ke liye best guidance.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=sameer",
  },
  {
    name: "Pooja Singh",
    comment: "Ab trade lene me confidence aa gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=pooja",
  },
  {
    name: "Anjali Gupta",
    comment: "Best course for beginners.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=anjali",
  },
  {
    name: "Sneha Patel",
    comment: "Ab overtrading band kar di.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=sneha",
  },
  {
    name: "Divyansh S.",
    comment: "अब FOMO control kar liya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=divyansh",
  },
  {
    name: "Ankita M.",
    comment: "Very useful content.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=ankita",
  },
  {
    name: "Manav K.",
    comment: "अब clear strategy follow karta hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=manav",
  },
  {
    name: "Priya Sharma",
    comment: "Pehle loss hota tha, ab consistent profit ho raha hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=priya",
  },
  {
    name: "Neha Verma",
    comment: "Concepts bahut clearly samjhaye gaye hain.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=neha",
  },
  {
    name: "Ragini T.",
    comment: "Best investment for learning.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ragini",
  },
  {
    name: "Sandeep V.",
    comment: "अब profit consistency aa rahi hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=sandeep",
  },
  {
    name: "Amit Verma",
    comment: "Course lene ke baad mera confidence kaafi badh gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=amit",
  },
  {
    name: "Rohit Kumar",
    comment: "Simple language me samjhaya gaya hai, beginner ke liye best.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rohit",
  },
  {
    name: "Sneha Patel",
    comment: "Ab loss control karna seekh gaya hu.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=sneha",
  },
  {
    name: "Vikas Singh",
    comment: "Live examples ne sab clear kar diya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=vikas",
  },
  {
    name: "Anjali Mehta",
    comment: "Option buying pe best explanation mila.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=anjali",
  },
  {
    name: "Deepak Yadav",
    comment: "Risk management pe clarity mil gayi.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=deepak",
  },
  {
    name: "Pooja Gupta",
    comment: "Pehle random trade karta tha, ab proper setup follow karta hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=pooja",
  },
  {
    name: "Rahul Das",
    comment: "Strategy ka win rate kaafi acha hai.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=rahul",
  },
  {
    name: "Neha Kapoor",
    comment: "Chart reading ab easy lagta hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=neha",
  },
  {
    name: "Karan Malhotra",
    comment: "Premium behavior samajh me aa gaya finally.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=karan",
  },
  {
    name: "Arjun Nair",
    comment: "Intraday trading me consistency aayi hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=arjun",
  },
  {
    name: "Meena Iyer",
    comment: "Har topic detail me explain kiya hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=meena",
  },
  {
    name: "Suresh Reddy",
    comment: "Breakout strategy kaafi powerful hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=suresh",
  },
  {
    name: "Ritika Jain",
    comment: "Support resistance ka use properly seekha.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ritika",
  },
  {
    name: "Manish Chauhan",
    comment: "Loss kam ho gaya aur profit stable hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=manish",
  },
  {
    name: "Kavita Singh",
    comment: "Course worth every penny hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=kavita",
  },
  {
    name: "Nikhil Sharma",
    comment: "Scalping ke liye best guide mila.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=nikhil",
  },
  {
    name: "Ayesha Khan",
    comment: "Market ka fear ab khatam ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ayesha",
  },
  {
    name: "Varun Agarwal",
    comment: "Option chain ka use ab samajh aaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=varun",
  },
  {
    name: "Sanjay Mishra",
    comment: "Strategy clear aur practical hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=sanjay",
  },
  {
    name: "Ravi Kumar",
    comment: "Daily small profits bana pa raha hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ravi",
  },
  {
    name: "Komal Shah",
    comment: "Beginner friendly content hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=komal",
  },
  {
    name: "Gaurav Joshi",
    comment: "Mentorship bhi achi mili.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=gaurav",
  },
  {
    name: "Priyanka Das",
    comment: "Indicators ka sahi use seekha.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=priyanka",
  },
  {
    name: "Abhishek Singh",
    comment: "Trading psychology improve hui.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=abhishek",
  },
  {
    name: "Sunita Devi",
    comment: "Loss recovery strategy helpful hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=sunita",
  },
  {
    name: "Harsh Patel",
    comment: "Short time me bahut kuch seekhne ko mila.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=harsh",
  },
  {
    name: "Tanvi Desai",
    comment: "Charts ab clearly samajh aate hain.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=tanvi",
  },
  {
    name: "Yash Gupta",
    comment: "Course ka structure bahut accha hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=yash",
  },
  {
    name: "Mohit Bansal",
    comment: "Real trading examples best part hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=mohit",
  },
  {
    name: "Alok Tiwari",
    comment: "Discipline sikhaya gaya hai properly.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=alok",
  },
  {
    name: "Swati Sharma",
    comment: "Confidence build karne me help mila.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=swati",
  },
  {
    name: "Rajesh Verma",
    comment: "Pehle gambling karta tha, ab trading karta hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rajesh",
  },
  {
    name: "Nisha Arora",
    comment: "Step by step guidance diya hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=nisha",
  },
  {
    name: "Sahil Khan",
    comment: "Option Greeks samajh me aaye finally.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=sahil",
  },
  {
    name: "Deepa Nair",
    comment: "Practice se result milne laga.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=deepa",
  },
  {
    name: "Lokesh Kumar",
    comment: "Risk reward concept clear hua.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=lokesh",
  },
  {
    name: "Ishita Roy",
    comment: "Beginner se advance tak sab cover hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ishita",
  },
  {
    name: "Aman Gupta",
    comment: "Strategy ka accuracy acha hai.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=aman",
  },
  {
    name: "Ramesh Patel",
    comment: "Live market me apply kar raha hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ramesh",
  },
  {
    name: "Shivam Pandey",
    comment: "Trading journey easy ho gayi.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=shivam",
  },
  {
    name: "Pallavi Joshi",
    comment: "Har doubt clear kiya gaya hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=pallavi",
  },
  {
    name: "Nitin Agarwal",
    comment: "Short term me improvement dikha.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=nitin",
  },
  {
    name: "Seema Yadav",
    comment: "Simple aur effective strategy hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=seema",
  },
  {
    name: "Ankit Verma",
    comment: "Charts ka fear khatam ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ankit",
  },
  {
    name: "Divya Singh",
    comment: "Option buying best explain kiya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=divya",
  },
  {
    name: "Rajiv Mehta",
    comment: "Consistency aa rahi hai ab.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rajiv",
  },
  {
    name: "Kajal Sharma",
    comment: "Bahut useful course hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=kajal",
  },
  {
    name: "Vivek Dubey",
    comment: "Setup follow karke profit mila.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=vivek",
  },
  {
    name: "Preeti Jain",
    comment: "Learning experience amazing tha.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=preeti",
  },
  {
    name: "Tarun Arora",
    comment: "Indicators ka use sahi samjha.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=tarun",
  },
  {
    name: "Anurag Mishra",
    comment: "Strategy practical hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=anurag",
  },
  {
    name: "Ruchi Gupta",
    comment: "Trading easy lagne lagi.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ruchi",
  },
  {
    name: "Hemant Singh",
    comment: "Loss control me aaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=hemant",
  },
  {
    name: "Kiran Patel",
    comment: "Charts ka clarity mil gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=kiran",
  },
  {
    name: "Monika Sharma",
    comment: "Beginner ke liye best hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=monika",
  },
  {
    name: "Ashish Yadav",
    comment: "Market samajhna easy hua.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ashish",
  },
  {
    name: "Pankaj Kumar",
    comment: "Real examples bahut help kiye.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=pankaj",
  },
  {
    name: "Ritu Verma",
    comment: "Course ka content top notch hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ritu",
  },
  {
    name: "Ajay Singh",
    comment: "Trading confidence increase hua.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ajay",
  },
  {
    name: "Naveen Kumar",
    comment: "Scalping strategy useful hai.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=naveen",
  },
  {
    name: "Bhavna Shah",
    comment: "Concept clear ho gaye sab.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=bhavna",
  },
  {
    name: "Sandeep Tiwari",
    comment: "Pehle loss tha, ab profit hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=sandeep",
  },
  {
    name: "Geeta Devi",
    comment: "Simple language me explain kiya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=geeta",
  },
  {
    name: "Rohini Nair",
    comment: "Charts ka understanding strong hua.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rohini",
  },
  {
    name: "Vishal Gupta",
    comment: "Discipline seekha yaha se.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=vishal",
  },
  {
    name: "Alka Sharma",
    comment: "Strategy easy aur effective hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=alka",
  },
  {
    name: "Dinesh Patel",
    comment: "Profit consistency aayi hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=dinesh",
  },
  {
    name: "Sonia Kapoor",
    comment: "Best trading course so far.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=sonia",
  },
  {
    name: "Harish Kumar",
    comment: "Learning amazing thi.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=harish",
  },
  {
    name: "Neeraj Singh",
    comment: "Option trading ab easy hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=neeraj",
  },
  {
    name: "Juhi Jain",
    comment: "Support resistance clear hua.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=juhi",
  },
  {
    name: "Arvind Yadav",
    comment: "Trading fear khatam hua.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=arvind",
  },
  {
    name: "Rakesh Verma",
    comment: "Setup strong hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rakesh",
  },
  {
    name: "Simran Kaur",
    comment: "Course bahut helpful hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=simran",
  },
  {
    name: "Mayank Gupta",
    comment: "Profit stable ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=mayank",
  },
  {
    name: "Shalini Sharma",
    comment: "Confidence increase hua.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=shalini",
  },
  {
    name: "Kapil Dev",
    comment: "Real trading sikha yaha.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=kapil",
  },
  {
    name: "Anu Patel",
    comment: "Best for beginners.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=anu",
  },
  {
    name: "Gopal Singh",
    comment: "Loss kam hua.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=gopal",
  },
  {
    name: "Aditya Rao",
    comment: "Ab trade lene se pehle clear plan hota hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=aditya",
  },
  {
    name: "Nandini Iyer",
    comment: "Learning simple aur practical hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=nandini",
  },
  {
    name: "Prakash Shetty",
    comment: "Daily consistent profit ban raha hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=prakash",
  },
  {
    name: "Ritu Singh",
    comment: "Course ne trading mindset change kar diya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ritu",
  },
  {
    name: "Kunal Jain",
    comment: "Strategy ka accuracy kaafi acha hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=kunal",
  },
  {
    name: "Bhavesh Patel",
    comment: "Option buying clear ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=bhavesh",
  },
  {
    name: "Pooja Reddy",
    comment: "Charts ka fear completely khatam.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=pooja",
  },
  {
    name: "Anil Kumar",
    comment: "Risk management best part hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=anil",
  },
  {
    name: "Megha Sharma",
    comment: "Har concept easy language me hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=megha",
  },
  {
    name: "Rajat Gupta",
    comment: "Trading discipline aa gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rajat",
  },
  {
    name: "Sakshi Verma",
    comment: "Beginner ke liye perfect course.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=sakshi",
  },
  {
    name: "Harshit Yadav",
    comment: "Ab random trade nahi leta hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=harshit",
  },
  {
    name: "Deepali Singh",
    comment: "Confidence build ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=deepali",
  },
  {
    name: "Lokesh Gupta",
    comment: "Strategy follow karke profit mila.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=lokesh",
  },
  {
    name: "Nikita Shah",
    comment: "Charts ab clearly samajh aate hain.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=nikita",
  },
  {
    name: "Saurabh Mishra",
    comment: "Learning experience awesome tha.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=saurabh",
  },
  {
    name: "Rakesh Yadav",
    comment: "Loss control me aa gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rakesh",
  },
  {
    name: "Kriti Mehta",
    comment: "Short and simple explanation.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=kriti",
  },
  {
    name: "Manoj Verma",
    comment: "Option chain use karna seekha.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=manoj",
  },
  {
    name: "Aarti Gupta",
    comment: "Real examples bahut help kiye.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=aarti",
  },
  {
    name: "Chirag Jain",
    comment: "Trading ab easy lagta hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=chirag",
  },
  {
    name: "Seema Sharma",
    comment: "Best investment for learning.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=seema",
  },
  {
    name: "Vivek Singh",
    comment: "Market ka behavior samajh aaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=vivek",
  },
  {
    name: "Priyanshu Kumar",
    comment: "Strategy ka win rate acha hai.",
    rating: 4,
    profilePic: "https://i.pravatar.cc/150?u=priyanshu",
  },
  {
    name: "Neha Verma",
    comment: "Confidence increase hua hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=neha",
  },
  {
    name: "Arpit Agarwal",
    comment: "Indicators ka sahi use seekha.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=arpit",
  },
  {
    name: "Pallav Das",
    comment: "Course bahut structured hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=pallav",
  },
  {
    name: "Ananya Sharma",
    comment: "Trading me clarity mil gayi.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ananya",
  },
  {
    name: "Rajat Sinha",
    comment: "Profit stable ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rajat",
  },
  {
    name: "Divyansh Gupta",
    comment: "Setup simple aur powerful hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=divyansh",
  },
  {
    name: "Kiran Reddy",
    comment: "Intraday me consistency aayi.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=kiran",
  },
  {
    name: "Sonal Patel",
    comment: "Course worth every rupee hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=sonal",
  },
  {
    name: "Mukesh Sharma",
    comment: "Live examples best lage.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=mukesh",
  },
  {
    name: "Altaf Khan",
    comment: "Risk reward concept clear hua.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=altaf",
  },
  {
    name: "Rekha Devi",
    comment: "Step by step teaching hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rekha",
  },
  {
    name: "Shubham Tiwari",
    comment: "Ab losses kam ho gaye.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=shubham",
  },
  {
    name: "Rohan Kapoor",
    comment: "Strategy kaafi effective hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rohan",
  },
  {
    name: "Tanya Mehta",
    comment: "Charts samajhna easy ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=tanya",
  },
  {
    name: "Yogesh Kumar",
    comment: "Trading discipline improve hua.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=yogesh",
  },
  {
    name: "Ankit Jain",
    comment: "Confidence boost hua hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ankit",
  },
  {
    name: "Payal Sharma",
    comment: "Beginner se advance sab cover hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=payal",
  },
  {
    name: "Siddharth Singh",
    comment: "Ab proper setup follow karta hu.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=siddharth",
  },
  {
    name: "Deepak Chauhan",
    comment: "Trading me clarity aa gayi.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=deepak",
  },
  {
    name: "Nisha Gupta",
    comment: "Simple aur easy explanation.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=nisha",
  },
  {
    name: "Aman Verma",
    comment: "Option buying strong ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=aman",
  },
  {
    name: "Riya Patel",
    comment: "Learning experience top notch.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=riya",
  },
  {
    name: "Ashutosh Mishra",
    comment: "Daily profit banana start kiya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ashutosh",
  },
  {
    name: "Kavya Iyer",
    comment: "Course ka structure perfect hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=kavya",
  },
  {
    name: "Pradeep Kumar",
    comment: "Strategy reliable hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=pradeep",
  },
  {
    name: "Snehal Shah",
    comment: "Confidence kaafi badh gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=snehal",
  },
  {
    name: "Nitin Verma",
    comment: "Market fear khatam ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=nitin",
  },
  {
    name: "Bharti Singh",
    comment: "Charts ka clarity mil gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=bharti",
  },
  {
    name: "Abhinav Gupta",
    comment: "Indicators ka use samajh aaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=abhinav",
  },
  {
    name: "Ruchi Sharma",
    comment: "Trading easy ho gayi.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ruchi",
  },
  {
    name: "Harsh Agarwal",
    comment: "Profit consistency aa gayi.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=harsh",
  },
  {
    name: "Divya Jain",
    comment: "Learning simple hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=divya",
  },
  {
    name: "Ravindra Kumar",
    comment: "Strategy kaafi useful hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ravindra",
  },
  {
    name: "Anshu Patel",
    comment: "Best trading course mila.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=anshu",
  },
  {
    name: "Vikas Gupta",
    comment: "Real trading sikha.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=vikas",
  },
  {
    name: "Simran Sharma",
    comment: "Concept clear ho gaye.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=simran",
  },
  {
    name: "Ajit Singh",
    comment: "Discipline build hua.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ajit",
  },
  {
    name: "Monika Verma",
    comment: "Confidence improve hua.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=monika",
  },
  {
    name: "Rohit Sinha",
    comment: "Trading smooth ho gayi.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rohit",
  },
  {
    name: "Gaurav Patel",
    comment: "Strategy follow karke profit mila.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=gaurav",
  },
  {
    name: "Pooja Jain",
    comment: "Charts ab clear lagte hain.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=pooja",
  },
  {
    name: "Manish Gupta",
    comment: "Loss kam ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=manish",
  },
  {
    name: "Naveen Sharma",
    comment: "Best learning platform hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=naveen",
  },
  {
    name: "Isha Kapoor",
    comment: "Short time me improvement mila.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=isha",
  },
  {
    name: "Kunal Verma",
    comment: "Trading confidence strong hua.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=kunal",
  },
  {
    name: "Sanjana Singh",
    comment: "Course kaafi helpful hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=sanjana",
  },
  {
    name: "Rajeev Mishra",
    comment: "Daily trading better ho rahi.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=rajeev",
  },
  {
    name: "Anuradha Sharma",
    comment: "Strategy simple hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=anuradha",
  },
  {
    name: "Ritesh Gupta",
    comment: "Profit stable ho gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=ritesh",
  },
  {
    name: "Mehul Shah",
    comment: "Learning clear hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=mehul",
  },
  {
    name: "Suman Yadav",
    comment: "Trading fear gone.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=suman",
  },
  {
    name: "Aakash Singh",
    comment: "Best explanation mila.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=aakash",
  },
  {
    name: "Neelam Devi",
    comment: "Charts easy ho gaye.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=neelam",
  },
  {
    name: "Tarun Gupta",
    comment: "Setup strong hai.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=tarun",
  },
  {
    name: "Pankaj Verma",
    comment: "Option buying best explain hua.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=pankaj",
  },
  {
    name: "Jyoti Sharma",
    comment: "Confidence aa gaya.",
    rating: 5,
    profilePic: "https://i.pravatar.cc/150?u=jyoti",
  },
];

// Har 1 ghante mein ek baar review post hoga (0 * * * *)
cron.schedule("0 * * * *", async () => {
  try {
    // Har baar pool se ek random index uthao
    const randomIndex = Math.floor(Math.random() * reviewPool.length);
    const randomData = reviewPool[randomIndex];
    const randomReview = reviewPool[randomIndex];

    console.log(`Attempting to post review for: ${randomReview.name}`);

    // Direct Collection entry validation bypass ke liye
    await Review.collection.insertOne({
      username: randomReview.name,
      name: randomReview.name,
      profilePic: randomData.profilePic,
      rating: randomReview.rating,
      comment: randomReview.comment,
      userId: new mongoose.Types.ObjectId(),
      status: "approved",
      createdAt: new Date(),
    });

    console.log(`✅ SUCCESS: Random Review posted by ${randomReview.name}`);
  } catch (err) {
    console.error("❌ DB SEAM ERROR:", err.message);
  }
});

// 🔥 RUN
async function run() {
  const reviews = await Review.find({ replied: false });

  // fake req, res (simple)
  const req = { body: { reviews } };

  const res = {
    json: (data) => console.log("DONE", data),
    status: () => ({ json: (data) => console.log("ERROR", data) }),
  };

  await handleAutoReply(req, res);
}

run();
